import { ReactNode } from 'react'
import './globals.css'
import { Roboto } from 'next/font/google'
import Providers from './providers'
import SideDrawer from '@/components/drawer/SideDrawer'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  visualViewport: 'initial-scale=1, width=device-width',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <Providers>
        <body className={roboto.className}>
          <SideDrawer>{children}</SideDrawer>
        </body>
      </Providers>
    </html>
  )
}
